name: Run Semantic Release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    name: Do Semantic Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN_RELEASE: ${{ secrets.GH_TOKEN_RELEASE }}
        run: |
          echo "Refreshing GitHub tags...";
          git fetch --tags

          echo "Generating release info...";
          git for-each-ref --sort=-committerdate --count=5 --format='%(contents:body)' refs/tags > RELEASE.md
          cat RELEASE.md

          echo "Running semantic release...";
          npm ci --loglevel verbose --legacy-peer-deps
          npm run-script semantic:release
